#feature for User and Auth routes with protection and validations
Procech20/BackEnd-JusticeChatBot-Challenge pull request #8
Opened 2021-03-12 08:55 UTC by Procech20

**What does the PR do?**

User and auth CRUD functionalities with validation and protection

**How is it implemented?**

_User routes:_

GET api/v1/techblogs/users
GET api/v1/techblogs/users/:id
POST api/v1/techblogs/users
PATCH api/v1/techblogs/users/:id
DELETE api/v1/techblogs/users/:id

_Auth routes:_

GET api/v1/techblogs/auth/login
GET api/v1/techblogs/auth/me
POST api/v1/techblogs/auth/register

**Validation and protection to the routes are also included.**

_*Some validations mentioned in the blog PR are well initialized in this one_

2021-03-12 10:46 UTC, Code-250 approved these changes

2021-03-12 11:19 UTC, RedJanvier requested changes
You did not follow my instructions! You are not using OOP nor Services!

2021-03-12 11:19 UTC, RedJanvier commented on src/App/controllers/user.js
> +export const getUsers = asyncHandler(async(req, res, next) => {
You need to export a Class and not an individual function.
Group all controllers into a single class.

2021-03-12 11:19 UTC, RedJanvier commented on src/App/controllers/user.js
> +import Models from '../../Database/models/server';
No models import is allowed in your controller! You need to move the models in services.
Your API must be ACID compliant as discussed in yesterday's meeting.

2021-03-12 11:19 UTC, RedJanvier commented on src/App/controllers/auth.js
> +import bcrypt from 'bcryptjs';
Please refer to the users controller to update this one too.

2021-03-12 11:19 UTC, RedJanvier commented on src/App/helpers/encryption.js
> +import bcrypt from 'bcryptjs';
This file has not been used! Please make sure to use it instead of what you did in your controllers!

2021-03-12 11:19 UTC, RedJanvier commented on src/App/helpers/jwt.js
> +import 'dotenv/config';
Please update the file to export a class instead of individual functions and make sure you are using it not just having it.

2021-03-12 11:19 UTC, RedJanvier commented on src/App/middlewares/permission.js
> +export const isAdmin = asyncHandler(async (req, res, next) => {
Please transform this into a Permissions class and IsAdmin can be a property inside the class.

2021-03-12 11:19 UTC, RedJanvier commented on src/App/middlewares/token.js
> +    const token = req.headers.autho.split(' ')[1];
It doesn't make sense to do the same work twice. You can choose either to have this file or the protect.js file but not both! And the one you choose make sure it is made into a class.

2021-03-12 11:19 UTC, RedJanvier commented on src/App/middlewares/validator.js
> +import schema  from '../helpers/schema';
Same for this file must export a class not individual functions!

2021-03-12 11:19 UTC, RedJanvier commented on src/App/routes/user.js
> +    .post(token, isAdmin, protect, signupValidate, createUser);
It doesn't make sense at all to use token and protect which do the same exact or nearly close works!

2021-03-12 11:19 UTC, RedJanvier commented on src/App/utils/auth.js
> +const authenticateToken = async (req, res, next) => {
This has been done like 3 times now in your API!
This is totally similar to `/middlewares/token.js` and `/middlewares/protect.js` Why do you need it three times?

2021-03-12 11:19 UTC, RedJanvier commented on src/Database/services/user.js
> +export default async (param) => {
Every service must be a class such as `UserServices` and the function can be the method such as `findOne`

2021-03-12 11:19 UTC, RedJanvier commented on src/server.js
> +app.use('/api/v1/techblogs/blogs', blogs);
Please combine all your routes in routes `index.js` file not here please!

2021-03-12 11:19 UTC, RedJanvier commented on src/server.js
> +db.sequelize.sync();
Why did you bring back the sync?

2021-03-13 20:36 UTC, RedJanvier requested changes
Please fix your ESLint and make sure your are looking good because it is so messed up

2021-03-13 20:36 UTC, RedJanvier commented on src/App/controllers/user.js
> +import Models from '../../Database/models/server';
@Procech20 You haven't yet finished removing models from your controllers! how do you expect this to be valid if you are not using services yet!

2021-03-13 20:36 UTC, RedJanvier commented on src/App/routes/index.js
> +router.use('/api/v1/techblogs/blogs', blogs);
Can you move the routes prefix in the `src/index.js` so as to remain with a shorter route here please? This is to remove the repetitions.
```suggestion
router.use('/blogs', blogs);
```

2021-03-13 20:36 UTC, RedJanvier commented on src/server.js
> +app.use('/', routes);
You can use this to remove repetitions in `src/routes/index.js` by moving the repeated  part here 
```suggestion
app.use('/api/v1/techblogs', routes);
```

2021-03-13 20:36 UTC, RedJanvier commented on src/server.js
> +db.sequelize.sync({ alert: true});
I really wonder why are you adding this while you know it clears the database!???

2021-03-13 20:36 UTC, RedJanvier commented on src/Database/services/user.js
> +  };
You need to fix your linter! (EsLint) is not working on your end.

2021-03-13 20:36 UTC, RedJanvier commented on src/Database/seeders/20210301211952-user.js
> +      id: 1,
Why do you need to manually pass the id?

2021-03-13 20:36 UTC, RedJanvier commented on src/App/middlewares/token.js
> +class routeProtection{
Why not add the isAdmin check in this class?

2021-03-13 20:36 UTC, RedJanvier commented on src/App/middlewares/permission.js
> +      return ErrorResponse(res, 401, 'Only admin allowed to perform such action.');
Make sure that the status code you are sending is correct!!!

2021-03-13 20:36 UTC, RedJanvier commented on src/App/helpers/jwt.js
> +static async encryptPassword(password) {
Why do you have this helper to encrypt twice as in `helpers/encryption.js` and here?

2021-03-13 20:36 UTC, RedJanvier commented on src/App/helpers/encryption.js
> +import bcrypt from 'bcryptjs';
@Procech20 why did you resolve this comment without fixing the issue?

2021-03-13 20:36 UTC, RedJanvier commented on src/App/controllers/blog.js
>  const { Blog } = Models;
Create a Service for this one just as you did for Users.

2021-03-13 20:36 UTC, RedJanvier commented on src/App/controllers/auth.js
> +      const token = jwt.sign(
Why aren't you using a helper you have for this?

2021-03-13 20:36 UTC, RedJanvier commented on src/App/controllers/auth.js
> +import Models from '../../Database/models/server'
Why aren't you using the service for this?

2021-03-13 20:36 UTC, RedJanvier commented on src/App/controllers/auth.js
> +import successRes from '../utils/succHandler';
You need to combine `SuccessRes` and `ErrorResponse` in a single class for responding Please!

Make sure to combine some other related functions.

2021-03-15 19:58 UTC, RedJanvier approved these changes
LGTM

2021-03-15 19:59 UTC, merged